"""more  table

Revision ID: 51a87e85213e
Revises: 8d0b3efe3f27
Create Date: 2022-07-08 12:16:33.880338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a87e85213e'
down_revision = '8d0b3efe3f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cards', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'workspace_id')
    # ### end Alembic commands ###
