"""create indexes

Revision ID: f9340b586b5a
Revises: c870e06c8bd9
Create Date: 2022-07-10 14:11:59.965341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9340b586b5a'
down_revision = 'c870e06c8bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'index',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
