"""create indexe

Revision ID: c870e06c8bd9
Revises: 51a87e85213e
Create Date: 2022-07-10 11:05:07.387814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c870e06c8bd9'
down_revision = '51a87e85213e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'index')
    # ### end Alembic commands ###
