"""string alter 250

Revision ID: 5f590e78d1a6
Revises: 6e23ba9190a7
Create Date: 2022-07-11 18:47:48.597526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f590e78d1a6'
down_revision = '6e23ba9190a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'index',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
